image: studiocentauri/conan:gcc-9.3.0
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the engine"
    - chmod +x ./ci/build.sh
    - ./ci/build.sh

doctest:
  stage: test
  script: 
    - echo "Performing tests"
    - chmod +x ./ci/test.sh
    - ./ci/test.sh
  artifacts:
    when: always
    reports:
      junit: ./report.xml

docs:
  stage: deploy
  script:
    - echo "Deploying"
    - chmod +x ./ci/deploy.sh
    - ./ci/deploy.sh
