stages:
  # - build
  - deploy

# TODO: Fix the spdlog linker error
# build:
#   stage: build
#   image: studiocentauri/conan:gcc-9.3.0
#   script:
#     - echo "Building the engine"
#     - sudo chmod +x ./ci/build.sh
#     - ./ci/build.sh
#     - echo "Performing tests"
#     - sudo chmod +x ./ci/test.sh
#     - ./ci/test.sh
#   artifacts:
#     when: always
#     reports:
#       junit: ./report.xml

docs:
  stage: deploy
  image: studiocentauri/sphinx:latest
  script:
    - echo "Building documentation"
    - chmod +x ./ci/docs.sh
    - ./ci/docs.sh
